name: Backend-STAGING deployment

# Trigger on push filter by branch
on:
  push:
    branches:
      - staging_back
jobs:
  front_build:
    runs-on: ubuntu-latest
    env:
      SERVER: fid@68.183.171.182
      REMOTE_DIR: ~/dd/staging
      BRANCH: staging_back
    steps:
      - name: Getting latest version on the server
        run: |
          eval `ssh-agent`
          ssh-add - <<< "${{secrets.DO_KEY}}"
          mkdir ~/.ssh
          echo > ~/.ssh/known_hosts
          ssh-keyscan 68.183.171.182 > ~/.ssh/known_hosts
          ssh "$SERVER" \
          "cd "$REMOTE_DIR" && \
          git fetch && \
          git checkout "$BRANCH""
      - name: Install dependencies on the backend
        run: |
          ssh "$SERVER" \
          "cd "$REMOTE_DIR"/backend && \
          npm install --only=production"
      # - name: Run DB migrations
      #   run: |
      #     ssh "$SERVER" \
      #     "cd "$REMOTE_DIR"/backend && \
      #     npm run migration:run"
      # - name: Run DB migrations
      #   run: |
      #     ssh "$SERVER" \
      #     "cd "$REMOTE_DIR" && pm2 restart all"