name: Frontend-STAGING deployment

# Trigger on push
on:
  push:
    branches:
      - staging_front
jobs:
  build:
    name: Frontend build and deploy
    runs-on: ubuntu-latest
  - uses: actions/checkout@v2
    steps:
    - checkout
    - name: Instalando dependencias
      run: ls
      run: pwd
      run: node -v
      run: npm -v

    