name: Frontend-STAGING deployment

# Trigger on push
on:
  push:
    branches:
      - staging_front
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Getting latest version
        run: git checkout .
        run: ls
      - id: Instalando dependencias
        run: |
          pwd
          ls
          node -v
          npm -v