name: Frontend-STAGING deployment

# Trigger on push filter by branch
on:
  push:
    branches:
      - staging_front
jobs:
  front_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Getting latest version
        run: git checkout
      - run: ls
      - name: Instalando dependencias
        run: |
          cd frontend
          npm install
      - name: Build
        run: |
          cd frontend
          npm run build
          cd dist
          ls
      - add_ssh_keys:
          fingerprints:
            - "48:52:f1:2a:86:3a:fe:a8:5b:c9:25:fd:3e:c3:d2:c1"
      - run: ssh-keyscan 68.183.171.182 > ~/.ssh/known_hosts
      - run:
          name: Deleting previous files
          command: |
            ssh fid@68.183.171.182 \
            "cd ~/dd/staging && \
            yes | rm -r public"
      - name: Sending front static files to server
        run: |
          cd frontend/dist
          scp -r ./spa fid@68.183.171.182:~/dd/staging/public
