name: Frontend-STAGING deployment

# Trigger on push filter by branch
on:
  push:
    branches:
      - staging_front
jobs:
  front_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Getting latest version
        run: git checkout
      - name: check folder
        run: ls
      - name: Instalando dependencias
        run: |
          pwd
          ls
          node -v
          npm -v