name: Frontend-STAGING deployment

# Trigger on push filter by branch
on:
  push:
    branches:
      - staging_front
jobs:
  front_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Getting latest version
        run: git checkout
      - run: ls
      - name: Instalando dependencias
        run: |
          cd frontend
          npm install
      - name: Build
        run: |
          cd frontend
          npm run build
          cd dist
          ls