name: Frontend-STAGING deployment

# Trigger on push filter by branch
on:
  push:
    branches:
      - staging_front
jobs:
  front_build:
    runs-on: ubuntu-latest
    env:
      SERVER: fid@68.183.171.182
    steps:
      - uses: actions/checkout@v2
      - name: Getting latest version
        run: git checkout
      - name: Adding ssh
        run: |
          eval `ssh-agent`
          ssh-add - <<< "${{secrets.DO_KEY}}"
      - name: Probando ssh 
        run: |
          echo $SERVER
          echo "$SERVER"
          ssh "$SERVER" \
          "pwd"
      # - name: Instalando dependencias
      #   run: |
      #     cd frontend
      #     npm install
      # - name: Build
      #   run: |
      #     cd frontend
      #     npm run build
      #     cd dist
      #     ls
      # - run: ssh-keyscan 68.183.171.182 > ~/.ssh/known_hosts
      # - name: Deleting previous files
      #   run: |
      #       ssh fid@68.183.171.182 \
      #       "cd ~/dd/staging && \
      #       yes | rm -r public"
      # - name: Sending front static files to server
      #   run: |
      #     cd frontend/dist
      #     scp -r ./spa fid@68.183.171.182:~/dd/staging/public
