name: Frontend-STAGING deployment

# Trigger on push filter by branch
on:
  push:
    branches:
      - staging_front
jobs:
  front_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Getting latest version
        run: git checkout
      - name: Starting ssh-agent
        run: eval `ssh-agent -s`
      - name: Adding ssh
        run: echo "${{secrets.DO_KEY}}" | ssh-add
      # - name: Instalando dependencias
      #   run: |
      #     cd frontend
      #     npm install
      # - name: Build
      #   run: |
      #     cd frontend
      #     npm run build
      #     cd dist
      #     ls
      # - run: ssh-keyscan 68.183.171.182 > ~/.ssh/known_hosts
      # - name: Deleting previous files
      #   run: |
      #       ssh fid@68.183.171.182 \
      #       "cd ~/dd/staging && \
      #       yes | rm -r public"
      # - name: Sending front static files to server
      #   run: |
      #     cd frontend/dist
      #     scp -r ./spa fid@68.183.171.182:~/dd/staging/public
